v3.2.0 release (#124)
* Add zenodo badge [skip ci]

* Test cond on constant rate

* test constant_rate_shift with cond

* Add test sim_time_dependent

* Add sim_trait_dependent cond test

* Fix sim_constant_rate_shift cond test

* Lint

* More stringent constant_rate test

* Better test title

* fix constant_rate_shift test

* Typo

* More sim_time_dep cond test

* More trait_dependent sim cond tests

* test conditioning in relaxed rate

* Remove duplicated tests

* Add 2 type cond warning. Closes #123

* Fix cond relaxed rate gam test

* Better warning text. Closes #123

* Lint

* Move over tests from DAISIEtesting

* No lintrbot

* Increase travis wait time

* Test warning of cond with 2 types

* Split format_CS_sampled_stt and format_CS_trait files

* abuse split-rate model with gamma = 0

* abuse time dependent model with gamma = 0

* Remove some input checks

* Better tests sim_core_1_4a

* test abuse and verbose DAISIE sim time dep

* test abuse sim_core_trait_dependent

* test no colonization happening returining 0 on stt

* trait sims don't take nonoceanic pars

* Delete DAISIE_single_branch

* Add are_rates test

* Better check format tests

* Fix typo

* Remove lingering nonoceanic pars in traits tests

* Better is_simulation_outputs name checking

* added higher subdivisions limit to integral_peak

* added rel.tol to integral_peak

* changed abs.tol to 1e-10

* changed integration to catch errors and return -Inf

* changed rho to log gamma distribution and integrand to sum

* removed if statement to catch integration errors

* removed stop.on.error in integration

* manual merge with 'hanno'

Signed-off-by: Hanno <h.hildenbrandt@rug.nl>

* builds,install & runs on Linux
source package added

Signed-off-by: Hanno <h.hildenbrandt@rug.nl>

* Updated version and documentation

* useDynLib in DAISIE-package.R, renewed documentation

* useDynLib in DAISIE-package.R, renewed documentation

* useDynLib in DAISIE-package.R, renewed documentation

* No export pipe just import from magrittr

* Correct appveyor.yml

* logos and AppVeyor status in README

* indent

* lint

* Progress correct brts ONEcolonist #125

* Only remove youngest_col if in vector. Progress #125

* Assert that youngest_col_time must be in btimes_all_clado_desc. Progress #125

* Format

* Add comments and asserts. Remove else

* Adjust refernce progress #125

* Add /pics to .Rbuildignore

* Try adding col times, removing youngest. Progress #125

* Remove appveyor setup

* Go GHA

* GHA on onecolonist_fix

* Switch to else if. Progress #125

* Fix references after testing. Progress #125

* Rename other_clades_same_ancestor to all_colonisations. Lint. Progress #125

* Better CI checks for testing

* seq_along() not seq_len(). Progress #125

* Better doc. Progress #125

* Fix reference test CS_full_stt. Progress #125

* other_clades_same_ancestor -> all_colonisations. Progress #125

* other_clades_same_ancestor -> all_colonisations in core_1_4.
Consider removing, changed to pass tests. Progress #125

* Better skips

* Expand ONEcolonist hedge case coverage. Progress #125

* Comment temp code

* Fix reference. Progress #125

* use NULL stt_table for testing. Progress #125

* Remove 1_4 and 1_5 functions and tests

* Legacy functions removed from tests. Progress #126

* Remove more legacy code and tests. Progress #126

* V with single string w/ all times. Progress #125

* DAISIE_ONEcolonist returns all_event_times. Closes #125

* Update test-format_CS references. Progress #125

* Add $all_colonisations reference tests. Progress #125

* Add and rearrange ONEcolonist tests. Progress #125

* Remove unnecessary section. Close #125

* Sort all_colonisations from oldest to youngest. #125

* Expand tests and add test for 2 clado 1 nonendemic. #125

* Remove get_brts_mya(). Progress #126

* create_island() is internal. Progress #126

* Don't export DAISIE_make_global(). Progress #126

* Fix ONEcolonist documentation

* Minor formatting

* Use improved GHA yaml

* Remove travis

* Faster example in constant_rate

* MinAge and better input support in DAISIE_dataprep

* Fix table

* Format pic

* Try travis again

* No roxygen doc on .Rproj

* Travis in right place

* Don't depend on Rcpp, RcppEigen, BH

* Delete top level files

* Buiild on Windows R4.0.2, Rtools40

Signed-off-by: Hanno <h.hildenbrandt@rug.nl>

* Windows binary package added

Signed-off-by: Hanno <h.hildenbrandt@rug.nl>

* Linux: devtools::check pass

Signed-off-by: Hanno <h.hildenbrandt@rug.nl>

* Try Rcpp, RcppEigen, BH on imports

* Rcpp, RcppEigen, BH on Imports

* Don't run on PR. Install doMC on unix

* Rcpp, RcppEigen, BH on Depends

* still trying

* R CMD check passes on Windows (R 3.6.3)
R CMD check passes on Linux (R 3.6.3)

Signed-off-by: Hanno <h.hildenbrandt@rug.nl>

* Install ggtree

* biocViews: to install ggtree instead

* No longer use travis

* date change

* invoke_IW to test

* Bug fix dopri5 and documentation

* documentation

* Solve
 Error: function 'enterRNGScope' not provided by package 'Rcpp'
as outlined on
https://github.com/immunogenomics/LISI/blob/master/NAMESPACE

* Depend on specific setup-r tag

See similar issue https://github.com/rsetienne/DDD/pull/29

* GHA on macOS_fix

* Use full SHA

* Check if new test breaks covr

* Add skip message

* Don't define functions in tests

* lint 2 integration tests

* lint rate-shift and IW vs CS integration tests

* Tweak time_dep ML WIP test

* 2 type integration test lint

* Remove redundant test-integration_tests

* Informative comment on parallel test fix

* Try loading Rcpp in tests

* Avoid coverage check on solver test

* Change flag location

* Correct nocov flags

* Split loglik_IW_solver and add to .covrignore

* covr output in GHA output

* Fix syntax

* Remove Rcpp library call

* skip_on_covr() and remove #nocov flags

* Just run codecov

* Delete wrong argument

* Add @xieshu95's ORCID

* Add @joshwlambert's ORCID

* Add a NEWS.md file to track changes to the package

* Add DAISIE_macOS instructions

* Update NEWS.md to match v3.2.0 release notes

* Add Big Sur note on README.md

* Typo

* setup-r@v1 again

See Neves-P/DAISIErobustness/cb6ae80f545f01e8a2ebe0c134f915d8f804c7b4

* Add LICENSE file

* arrows instead of =

* Solving numerical problems with logcondprob

* Improving numerical accuracy logcond

* Modified test to conform to new logcond

* cleaning up logcond

* Improving logcond

* bug fix

* Resolving numerical issues near 0 in integration across parameters

* passing mean and sd

* fixed bug

* Correctly format doi

* relaxed rate in NEWS.md

* Add note on logcondprob fix

* Update date

* updated relaxed_rate loglik

* Use midpoint of function for better approximation

* reduce approx threshold to 0.01 for relaxed-rate

* Add @rscherrer's ORCID

* Touch up references and authors

* @HHildenbrandt is an author

* changed approx threshold to 1 and change approximation to DAISIE_loglik

* added tests for DAISIE_loglik_integrate

* tidy DAISIE_loglik_integrate

Co-authored-by: Pedro Neves <10762799+Neves-P@users.noreply.github.com>
Co-authored-by: Neves-P <p.m.santos.neves@rug.nl>
Co-authored-by: joshwlambert <j.w.l.lambert@rug.nl>
Co-authored-by: rsetienne <rampaletienne@gmail.com>
Co-authored-by: = <=>